// <auto-generated />
using System;
using System.Collections.Generic;
using KelimeOyunu.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KelimeOyunu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Elma"
                        },
                        new
                        {
                            Id = new Guid("d0000002-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Muz"
                        },
                        new
                        {
                            Id = new Guid("d0000003-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Portakal"
                        },
                        new
                        {
                            Id = new Guid("d0000004-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Çilek"
                        },
                        new
                        {
                            Id = new Guid("d0000005-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Karpuz"
                        },
                        new
                        {
                            Id = new Guid("d0000006-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Üzüm"
                        },
                        new
                        {
                            Id = new Guid("d0000007-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Kiraz"
                        },
                        new
                        {
                            Id = new Guid("d0000008-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Şeftali"
                        },
                        new
                        {
                            Id = new Guid("d0000009-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Armut"
                        },
                        new
                        {
                            Id = new Guid("d0000010-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Kavun"
                        },
                        new
                        {
                            Id = new Guid("d0000011-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Kırmızı"
                        },
                        new
                        {
                            Id = new Guid("d0000012-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Mavi"
                        },
                        new
                        {
                            Id = new Guid("d0000013-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Yeşil"
                        },
                        new
                        {
                            Id = new Guid("d0000014-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Sarı"
                        },
                        new
                        {
                            Id = new Guid("d0000015-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Siyah"
                        },
                        new
                        {
                            Id = new Guid("d0000016-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Beyaz"
                        },
                        new
                        {
                            Id = new Guid("d0000017-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Turuncu"
                        },
                        new
                        {
                            Id = new Guid("d0000018-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Mor"
                        },
                        new
                        {
                            Id = new Guid("d0000019-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Text = "Pembe"
                        },
                        new
                        {
                            Id = new Guid("d0000020-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Kedi"
                        },
                        new
                        {
                            Id = new Guid("d0000021-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Köpek"
                        },
                        new
                        {
                            Id = new Guid("d0000022-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "At"
                        },
                        new
                        {
                            Id = new Guid("d0000023-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Aslan"
                        },
                        new
                        {
                            Id = new Guid("d0000024-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Kaplan"
                        },
                        new
                        {
                            Id = new Guid("d0000025-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Fil"
                        },
                        new
                        {
                            Id = new Guid("d0000026-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Tavuk"
                        },
                        new
                        {
                            Id = new Guid("d0000027-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Kuş"
                        },
                        new
                        {
                            Id = new Guid("d0000028-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Balık"
                        },
                        new
                        {
                            Id = new Guid("d0000029-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Tavşan"
                        },
                        new
                        {
                            Id = new Guid("d0000030-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "Türkiye"
                        },
                        new
                        {
                            Id = new Guid("d0000031-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "Almanya"
                        },
                        new
                        {
                            Id = new Guid("d0000032-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "Fransa"
                        },
                        new
                        {
                            Id = new Guid("d0000033-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "İngiltere"
                        },
                        new
                        {
                            Id = new Guid("d0000034-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "İtalya"
                        },
                        new
                        {
                            Id = new Guid("d0000035-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "İspanya"
                        },
                        new
                        {
                            Id = new Guid("d0000036-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "ABD"
                        },
                        new
                        {
                            Id = new Guid("d0000037-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "Japonya"
                        },
                        new
                        {
                            Id = new Guid("d0000038-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Text = "Brezilya"
                        },
                        new
                        {
                            Id = new Guid("d0000039-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Futbol"
                        },
                        new
                        {
                            Id = new Guid("d0000040-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Basketbol"
                        },
                        new
                        {
                            Id = new Guid("d0000041-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Voleybol"
                        },
                        new
                        {
                            Id = new Guid("d0000042-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Tenis"
                        },
                        new
                        {
                            Id = new Guid("d0000043-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Yüzme"
                        },
                        new
                        {
                            Id = new Guid("d0000044-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Boks"
                        },
                        new
                        {
                            Id = new Guid("d0000045-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Atletizm"
                        },
                        new
                        {
                            Id = new Guid("d0000046-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Text = "Güreş"
                        },
                        new
                        {
                            Id = new Guid("d0000047-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Doktor"
                        },
                        new
                        {
                            Id = new Guid("d0000048-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Öğretmen"
                        },
                        new
                        {
                            Id = new Guid("d0000049-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Mühendis"
                        },
                        new
                        {
                            Id = new Guid("d0000050-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Avukat"
                        },
                        new
                        {
                            Id = new Guid("d0000051-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Polis"
                        },
                        new
                        {
                            Id = new Guid("d0000052-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Hemşire"
                        },
                        new
                        {
                            Id = new Guid("d0000053-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Pilot"
                        },
                        new
                        {
                            Id = new Guid("d0000054-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Text = "Aşçı"
                        },
                        new
                        {
                            Id = new Guid("d0000055-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Gitar"
                        },
                        new
                        {
                            Id = new Guid("d0000056-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Piyano"
                        },
                        new
                        {
                            Id = new Guid("d0000057-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Keman"
                        },
                        new
                        {
                            Id = new Guid("d0000058-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Davul"
                        },
                        new
                        {
                            Id = new Guid("d0000059-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Flüt"
                        },
                        new
                        {
                            Id = new Guid("d0000060-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Saz"
                        },
                        new
                        {
                            Id = new Guid("d0000061-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Klarnet"
                        },
                        new
                        {
                            Id = new Guid("d0000062-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Text = "Ney"
                        },
                        new
                        {
                            Id = new Guid("d0000063-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Domates"
                        },
                        new
                        {
                            Id = new Guid("d0000064-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Biber"
                        },
                        new
                        {
                            Id = new Guid("d0000065-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Salatalık"
                        },
                        new
                        {
                            Id = new Guid("d0000066-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Patates"
                        },
                        new
                        {
                            Id = new Guid("d0000067-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Soğan"
                        },
                        new
                        {
                            Id = new Guid("d0000068-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Havuç"
                        },
                        new
                        {
                            Id = new Guid("d0000069-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Patlıcan"
                        },
                        new
                        {
                            Id = new Guid("d0000070-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Kabak"
                        },
                        new
                        {
                            Id = new Guid("d0000071-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Text = "Marul"
                        },
                        new
                        {
                            Id = new Guid("d0000072-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "İstanbul"
                        },
                        new
                        {
                            Id = new Guid("d0000073-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "Ankara"
                        },
                        new
                        {
                            Id = new Guid("d0000074-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "İzmir"
                        },
                        new
                        {
                            Id = new Guid("d0000075-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "Antalya"
                        },
                        new
                        {
                            Id = new Guid("d0000076-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "Bursa"
                        },
                        new
                        {
                            Id = new Guid("d0000077-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "Trabzon"
                        },
                        new
                        {
                            Id = new Guid("d0000078-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "Adana"
                        },
                        new
                        {
                            Id = new Guid("d0000079-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "Konya"
                        },
                        new
                        {
                            Id = new Guid("d0000080-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Text = "Gaziantep"
                        },
                        new
                        {
                            Id = new Guid("d0000081-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "BMW"
                        },
                        new
                        {
                            Id = new Guid("d0000082-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Mercedes"
                        },
                        new
                        {
                            Id = new Guid("d0000083-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Audi"
                        },
                        new
                        {
                            Id = new Guid("d0000084-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Toyota"
                        },
                        new
                        {
                            Id = new Guid("d0000085-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Volkswagen"
                        },
                        new
                        {
                            Id = new Guid("d0000086-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Ford"
                        },
                        new
                        {
                            Id = new Guid("d0000087-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Honda"
                        },
                        new
                        {
                            Id = new Guid("d0000088-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Renault"
                        },
                        new
                        {
                            Id = new Guid("d0000089-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Text = "Fiat"
                        },
                        new
                        {
                            Id = new Guid("d0000090-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Çay"
                        },
                        new
                        {
                            Id = new Guid("d0000091-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Kahve"
                        },
                        new
                        {
                            Id = new Guid("d0000092-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Su"
                        },
                        new
                        {
                            Id = new Guid("d0000093-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Ayran"
                        },
                        new
                        {
                            Id = new Guid("d0000094-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Kola"
                        },
                        new
                        {
                            Id = new Guid("d0000095-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Limonata"
                        },
                        new
                        {
                            Id = new Guid("d0000096-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Süt"
                        },
                        new
                        {
                            Id = new Guid("d0000097-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Meyve Suyu"
                        },
                        new
                        {
                            Id = new Guid("d0000098-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Gül"
                        },
                        new
                        {
                            Id = new Guid("d0000099-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Papatya"
                        },
                        new
                        {
                            Id = new Guid("d0000100-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Lale"
                        },
                        new
                        {
                            Id = new Guid("d0000101-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Orkide"
                        },
                        new
                        {
                            Id = new Guid("d0000102-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Karanfil"
                        },
                        new
                        {
                            Id = new Guid("d0000103-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Menekşe"
                        },
                        new
                        {
                            Id = new Guid("d0000104-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Ayçiçeği"
                        },
                        new
                        {
                            Id = new Guid("d0000105-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Text = "Zambak"
                        },
                        new
                        {
                            Id = new Guid("d0000106-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Aksiyon"
                        },
                        new
                        {
                            Id = new Guid("d0000107-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Komedi"
                        },
                        new
                        {
                            Id = new Guid("d0000108-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Korku"
                        },
                        new
                        {
                            Id = new Guid("d0000109-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Dram"
                        },
                        new
                        {
                            Id = new Guid("d0000110-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Bilim Kurgu"
                        },
                        new
                        {
                            Id = new Guid("d0000111-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Romantik"
                        },
                        new
                        {
                            Id = new Guid("d0000112-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Animasyon"
                        },
                        new
                        {
                            Id = new Guid("d0000113-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Text = "Belgesel"
                        },
                        new
                        {
                            Id = new Guid("d0000114-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "Matematik"
                        },
                        new
                        {
                            Id = new Guid("d0000115-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "Türkçe"
                        },
                        new
                        {
                            Id = new Guid("d0000116-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "Fen Bilgisi"
                        },
                        new
                        {
                            Id = new Guid("d0000117-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "Tarih"
                        },
                        new
                        {
                            Id = new Guid("d0000118-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "Coğrafya"
                        },
                        new
                        {
                            Id = new Guid("d0000119-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "İngilizce"
                        },
                        new
                        {
                            Id = new Guid("d0000120-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "Müzik"
                        },
                        new
                        {
                            Id = new Guid("d0000121-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Text = "Beden Eğitimi"
                        },
                        new
                        {
                            Id = new Guid("d0000122-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Tişört"
                        },
                        new
                        {
                            Id = new Guid("d0000123-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Pantolon"
                        },
                        new
                        {
                            Id = new Guid("d0000124-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Gömlek"
                        },
                        new
                        {
                            Id = new Guid("d0000125-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Etek"
                        },
                        new
                        {
                            Id = new Guid("d0000126-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Ceket"
                        },
                        new
                        {
                            Id = new Guid("d0000127-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Kazak"
                        },
                        new
                        {
                            Id = new Guid("d0000128-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Şort"
                        },
                        new
                        {
                            Id = new Guid("d0000129-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Text = "Mont"
                        },
                        new
                        {
                            Id = new Guid("d0000130-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Tencere"
                        },
                        new
                        {
                            Id = new Guid("d0000131-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Bıçak"
                        },
                        new
                        {
                            Id = new Guid("d0000132-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Tabak"
                        },
                        new
                        {
                            Id = new Guid("d0000133-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Bardak"
                        },
                        new
                        {
                            Id = new Guid("d0000134-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Çatal"
                        },
                        new
                        {
                            Id = new Guid("d0000135-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Kaşık"
                        },
                        new
                        {
                            Id = new Guid("d0000136-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Tava"
                        },
                        new
                        {
                            Id = new Guid("d0000137-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Text = "Süzgeç"
                        },
                        new
                        {
                            Id = new Guid("d0000138-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Mars"
                        },
                        new
                        {
                            Id = new Guid("d0000139-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Jüpiter"
                        },
                        new
                        {
                            Id = new Guid("d0000140-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Venüs"
                        },
                        new
                        {
                            Id = new Guid("d0000141-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Satürn"
                        },
                        new
                        {
                            Id = new Guid("d0000142-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Merkür"
                        },
                        new
                        {
                            Id = new Guid("d0000143-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Neptün"
                        },
                        new
                        {
                            Id = new Guid("d0000144-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Uranüs"
                        },
                        new
                        {
                            Id = new Guid("d0000145-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Text = "Dünya"
                        },
                        new
                        {
                            Id = new Guid("d0000146-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Yunus"
                        },
                        new
                        {
                            Id = new Guid("d0000147-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Köpekbalığı"
                        },
                        new
                        {
                            Id = new Guid("d0000148-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Balina"
                        },
                        new
                        {
                            Id = new Guid("d0000149-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Ahtapot"
                        },
                        new
                        {
                            Id = new Guid("d0000150-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Denizanası"
                        },
                        new
                        {
                            Id = new Guid("d0000151-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Yengeç"
                        },
                        new
                        {
                            Id = new Guid("d0000152-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Karides"
                        },
                        new
                        {
                            Id = new Guid("d0000153-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Text = "Deniz Kaplumbağası"
                        },
                        new
                        {
                            Id = new Guid("d0000154-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Kebap"
                        },
                        new
                        {
                            Id = new Guid("d0000155-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Lahmacun"
                        },
                        new
                        {
                            Id = new Guid("d0000156-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Pide"
                        },
                        new
                        {
                            Id = new Guid("d0000157-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Döner"
                        },
                        new
                        {
                            Id = new Guid("d0000158-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Mantı"
                        },
                        new
                        {
                            Id = new Guid("d0000159-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "İskender"
                        },
                        new
                        {
                            Id = new Guid("d0000160-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Köfte"
                        },
                        new
                        {
                            Id = new Guid("d0000161-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Çorba"
                        },
                        new
                        {
                            Id = new Guid("d0000162-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Dolma"
                        },
                        new
                        {
                            Id = new Guid("d0000163-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Text = "Baklava"
                        },
                        new
                        {
                            Id = new Guid("d0000164-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "Python"
                        },
                        new
                        {
                            Id = new Guid("d0000165-0000-0000-0000-000000000000"),
                            IsPopular = true,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("d0000166-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "Java"
                        },
                        new
                        {
                            Id = new Guid("d0000167-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "C#"
                        },
                        new
                        {
                            Id = new Guid("d0000168-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "C++"
                        },
                        new
                        {
                            Id = new Guid("d0000169-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("d0000170-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "Go"
                        },
                        new
                        {
                            Id = new Guid("d0000171-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "Rust"
                        },
                        new
                        {
                            Id = new Guid("d0000172-0000-0000-0000-000000000000"),
                            IsPopular = false,
                            QuestionId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Text = "PHP"
                        });
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.GameRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveTurnPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("FoundAnswers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Player1Score")
                        .HasColumnType("integer");

                    b.Property<int>("Player2Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoundWinnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("GameRounds");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Player1RoundWins")
                        .HasColumnType("integer");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Player2RoundWins")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Category = "Yiyecek",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir meyve adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Category = "Genel",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir renk adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Category = "Hayvanlar",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir hayvan adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Category = "Coğrafya",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir ülke adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Category = "Spor",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir spor dalı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Category = "Meslekler",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir meslek adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Category = "Müzik",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir müzik aleti söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Category = "Yiyecek",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir sebze adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Category = "Coğrafya",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir şehir adı söyleyin (Türkiye)"
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Category = "Otomobil",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir araç markası söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Category = "Yiyecek",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir içecek adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Category = "Doğa",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir çiçek adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Category = "Eğlence",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir film türü söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Category = "Eğitim",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir okul dersi söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b6666666-6666-6666-6666-666666666666"),
                            Category = "Moda",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir giysi türü söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Category = "Ev",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Mutfakta bulunan bir eşya söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Category = "Bilim",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir gezegen adı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("b9999999-9999-9999-9999-999999999999"),
                            Category = "Hayvanlar",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir deniz canlısı söyleyin"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Category = "Yiyecek",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir Türk yemeği söyleyin"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Category = "Teknoloji",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Bir yazılım dili söyleyin"
                        });
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DiamondAmount")
                        .HasColumnType("integer");

                    b.Property<int>("GoldAmount")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Diamonds")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAdRewardTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalLosses")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Answer", b =>
                {
                    b.HasOne("KelimeOyunu.Core.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Friendship", b =>
                {
                    b.HasOne("KelimeOyunu.Core.Entities.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KelimeOyunu.Core.Entities.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.GameRound", b =>
                {
                    b.HasOne("KelimeOyunu.Core.Entities.GameSession", "GameSession")
                        .WithMany("Rounds")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KelimeOyunu.Core.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.GameSession", b =>
                {
                    b.HasOne("KelimeOyunu.Core.Entities.User", "Player1")
                        .WithMany("GameSessionsAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KelimeOyunu.Core.Entities.User", "Player2")
                        .WithMany("GameSessionsAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KelimeOyunu.Core.Entities.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Message", b =>
                {
                    b.HasOne("KelimeOyunu.Core.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KelimeOyunu.Core.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Transaction", b =>
                {
                    b.HasOne("KelimeOyunu.Core.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.GameSession", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("KelimeOyunu.Core.Entities.User", b =>
                {
                    b.Navigation("GameSessionsAsPlayer1");

                    b.Navigation("GameSessionsAsPlayer2");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("SentMessages");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
